---

  - name: Install keepalived
    apt: name=keepalived state=present

  - name: Copy keepalived MASTER configuration in place.
    template:
      src: keepalived.master.conf.j2
      dest: /etc/keepalived/keepalived.conf
      mode: 0644
    notify: restart keepalived
    when: ansible_hostname == 'haproxy1'

  - name: Copy keepalived BACKUP configuration in place.
    template:
      src: keepalived.backup.conf.j2
      dest: /etc/keepalived/keepalived.conf
      mode: 0644
    notify: restart keepalived
    when: ansible_hostname == 'haproxy2'

  - name: Ensure keepalived is started and enabled on boot.
    service: name=keepalived state=started enabled=yes